name: Package changelog

on:
#  push:
#    branches:
#      - release-please--branches--main
  workflow_dispatch:

env:
  REPOSITORY_OWNER: erkenes
  REPOSITORY_PROTOCOL: https://
  REPOSITORY_HOST: github.com
  REPOSITORY_NAME: monorepo-test

jobs:
  packages_split:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        package:
          -
            local_path: 'Packages/First.Package'
            repository_organization: 'erkenes'
            repository_name: 'monorepo-test-target-1'
            default_branch: 'main'
          -
            local_path: 'Packages/Second.Package'
            repository_organization: 'erkenes'
            repository_name: 'monorepo-test-target-2'
            default_branch: 'main'

    steps:
      - name: Create Changelog - Init Node (npm)
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install conventional-changelog-cli
        run: npm install -g conventional-changelog-cli

      - name: Create Changelog - Generate token
        id: generate_token_changelog
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92
        with:
          app_id: ${{ secrets.TOKEN_APP_ID }}
          private_key: ${{ secrets.TOKEN_APP_PRIVATE_KEY }}

      - uses: actions/checkout@v3
        with:
          repository: ${{ matrix.package.repository_organization }}/${{ matrix.package.repository_name }}
          ref: main
          token: ${{ steps.generate_token_changelog.outputs.token }}
          path: './temp/changelog/${{ matrix.package.repository_organization }}/${{ matrix.package.repository_name }}'
          fetch-depth: 0

      - name: Change folder to package temp
        run: cd ./temp/changelog/${{ matrix.package.repository_organization }}/${{ matrix.package.repository_name }}

      - name: Create Changelog - Generate changelog
        run: conventional-changelog -r 0 -p angular --infile ./temp/changelog/${{ matrix.package.repository_organization }}/${{ matrix.package.repository_name }}/CHANGELOG.md --outfile ${{ matrix.package.local_path}}/CHANGELOG.md

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: changelog2-${{ matrix.package.repository_organization }}-${{ matrix.package.repository_name }}
          path: ${{ matrix.package.local_path}}/CHANGELOG.md

      - name: Push Changelog - Commit and push
        uses: EndBug/add-and-commit@v7
        with:
          author_name: ${{ github.actor }}
          author_email: ${{ github.actor }}@users.noreply.github.com
          message: 'feat: Add changelog for ${{ matrix.package.repository }}'
          add: '${{ matrix.package.local_path}}/CHANGELOG.md'
          new_branch: release-main
          token: ${{ steps.generate_token_changelog.outputs.token }}
