#name: Package changelog
#
#on:
#  push:
#    branches:
#      - release-please--branches--main
#
#env:
#  REPOSITORY_OWNER: erkenes
#  REPOSITORY_PROTOCOL: https://
#  REPOSITORY_HOST: github.com
#  REPOSITORY_NAME: monorepo-test
#
#jobs:
#  packages_split:
#    runs-on: ubuntu-latest
#
#    strategy:
#      fail-fast: false
#      matrix:
#        package:
#          -
#            local_path: 'Packages/First.Package'
#            repository: 'erkenes/monorepo-test-target-1'
#            default_branch: 'main'
#          -
#            local_path: 'Packages/Second.Package'
#            repository: 'erkenes/monorepo-test-target-2'
#            default_branch: 'main'
#
#    steps:
#      - uses: actions/checkout@v3
#
#      # Create changelog
#      - name: Create Changelog - Generate token
#        id: generate_token_changelog
#        uses: tibdex/github-app-token@586e1a624db6a5a4ac2c53daeeded60c5e3d50fe
#        with:
#          app_id: ${{ secrets.TOKEN_APP_ID }}
#          private_key: ${{ secrets.TOKEN_APP_PRIVATE_KEY }}
#          permissions: >-
#            {"members": "write"}
#      - name: Create Changelog - Checkout repository
#        uses: actions/checkout@v3
#        with:
#          repository: ${{ matrix.package.repository }}
#          path: './__changelog/${{ matrix.package.repository }}'
#          ref: ${{ env.RELEASE_VERSION }}
#          token: ${{ steps.generate_token_changelog.outputs.token }}
#
#      - uses: actions/setup-node@v3
#        with:
#          node-version: 18
#          cache: 'npm'
#      - run: npm ci
#      - run: npm run changelog -- --infile ${{ matrix.package.local_path}}/CHANGELOG.md --same-file
#      -
#        name: Push Changelog - Commit and push
#        uses: EndBug/add-and-commit@v7
#        with:
#          author_name: ${{ github.actor }}
#          author_email: ${{ github.actor }}@users.noreply.github.com
#          message: 'feat: Add changelog for ${{ matrix.package.repository }}'
#          add: '${{ matrix.package.local_path}}/CHANGELOG.md'
#          new_branch: realase/${{ env.RELEASE_VERSION }}
#          token: ${{ steps.generate_token_changelog.outputs.token }}
