name: Monorepo Split

on:
  push:
    tags: [ '*.*.*' ]
  workflow_dispatch:

env:
  REPOSITORY_OWNER: erkenes
  REPOSITORY_PROTOCOL: https://
  REPOSITORY_HOST: github.com
  REPOSITORY_NAME: monorepo-test

jobs:
  packages_split:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        package:
          -
            local_path: 'Packages/First.Package'
            repository: 'erkenes/monorepo-test-target-1'
            default_branch: 'main'
          -
            local_path: 'Packages/Second.Package'
            repository: 'erkenes/monorepo-test-target-2'
            default_branch: 'main'

    steps:
      -
        name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92
        with:
          app_id: ${{ secrets.TOKEN_APP_ID }}
          private_key: ${{ secrets.TOKEN_APP_PRIVATE_KEY }}

      - uses: actions/checkout@v2

      # set current branch or tag
      - name: Set release version for branch or tag
        run: echo "RELEASE_VERSION=${{ github.ref }}" >> $GITHUB_ENV

      - uses: erkenes/monorepo-split-action@1.3.0
        with:
          access_token: 'x-access-token:${{ steps.generate_token.outputs.token }}'
          repository_protocol: ${{ env.REPOSITORY_PROTOCOL }}
          repository_host: ${{ env.REPOSITORY_HOST }}
          repository_organization: ${{ env.REPOSITORY_OWNER }}
          repository_name: ${{ env.REPOSITORY_NAME }}
          default_branch: ${{ matrix.package.default_branch }}
          target_branch: ${{ env.RELEASE_VERSION }}
          package_directory: ${{ matrix.package.local_path }}
          remote_repository: '${{ env.REPOSITORY_PROTOCOL }}${{ env.REPOSITORY_HOST }}/${{ matrix.package.repository }}.git'
          remote_repository_access_token: 'x-access-token:${{ steps.generate_token.outputs.token }}'
