name: Monorepo Split

on:
  push:
    branches:
      - main
    tags: [ '*.*.*' ]
  workflow_dispatch:

env:
  REPOSITORY_OWNER: erkenes
  REPOSITORY_PROTOCOL: https://
  REPOSITORY_HOST: github.com
  REPOSITORY_NAME: monorepo-test

jobs:
  packages_split:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        package:
          - local_path: 'Packages/First.Package'
            repository_organization: 'erkenes'
            repository_name: 'monorepo-test-target-1'
            default_branch: 'main'
          - local_path: 'Packages/Second.Package'
            repository_organization: 'erkenes'
            repository_name: 'monorepo-test-target-2'
            default_branch: 'main'

    steps:
      -
        name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92
        with:
          app_id: ${{ secrets.TOKEN_APP_ID }}
          private_key: ${{ secrets.TOKEN_APP_PRIVATE_KEY }}

      - uses: actions/checkout@v3

      # set current branch or tag
      - name: Set release version for branch or tag
        run: echo "RELEASE_VERSION=${{ github.ref }}" >> $GITHUB_ENV

      - uses: erkenes/monorepo-split-action@1.3.0
        with:
          access_token: 'x-access-token:${{ steps.generate_token.outputs.token }}'
          repository_protocol: ${{ env.REPOSITORY_PROTOCOL }}
          repository_host: ${{ env.REPOSITORY_HOST }}
          repository_organization: ${{ env.REPOSITORY_OWNER }}
          repository_name: ${{ env.REPOSITORY_NAME }}
          default_branch: ${{ matrix.package.default_branch }}
          target_branch: ${{ env.RELEASE_VERSION }}
          package_directory: ${{ matrix.package.local_path }}
          remote_repository: '${{ env.REPOSITORY_PROTOCOL }}${{ env.REPOSITORY_HOST }}/${{ matrix.package.repository_organization }}/${{ matrix.package.repository_name }}/.git'
          remote_repository_access_token: 'x-access-token:${{ steps.generate_token.outputs.token }}'

      # Create changelog
      - name: Create Changelog - Checkout repository
        uses: actions/checkout@v3
        with:
          repository: ${{ matrix.package.repository_organization }}/${{ matrix.package.repository_name }}/
          path: './temp/changelog/${{ matrix.package.repository_organization }}/${{ matrix.package.repository_name }}/'
          ref: ${{ env.RELEASE_VERSION }}
          token: ${{ steps.generate_token.outputs.token }}
      -
        name: Create Changelog - Init Node (npm)
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      -
        name: Create Changelog - Install NPM dependencies
        run: npm ci
      -
        name: Create Changelog - Generate changelog
        run: npm run changelog -- --infile ./temp/changelog/${{ matrix.package.repository_organization }}/${{ matrix.package.repository_name }}//CHANGELOG.md --outfile ${{ matrix.package.local_path}}/CHANGELOG.md

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: changelog-${{ matrix.package.repository_organization }}-${{ matrix.package.repository_name }}/
          path: ${{ matrix.package.local_path}}/CHANGELOG.md

  commit-changelog:
    needs: packages_split
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        package:
          - local_path: 'Packages/First.Package'
            repository_organization: 'erkenes'
            repository_name: 'monorepo-test-target-1'
            default_branch: 'main'
          - local_path: 'Packages/Second.Package'
            repository_organization: 'erkenes'
            repository_name: 'monorepo-test-target-2'
            default_branch: 'main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: changelog-${{ matrix.package.repository_organization }}-${{ matrix.package.repository_name }}/
          path: ${{ matrix.package.local_path}}/CHANGELOG.md

#      # Create changelog
#      - name: Create Changelog - Generate token
#        id: generate_token_changelog
#        uses: tibdex/github-app-token@586e1a624db6a5a4ac2c53daeeded60c5e3d50fe
#        with:
#          app_id: ${{ secrets.TOKEN_APP_ID }}
#          private_key: ${{ secrets.TOKEN_APP_PRIVATE_KEY }}
#      - name: Create Changelog - Checkout repository
#        uses: actions/checkout@v3
#        with:
#          repository: ${{ matrix.package.repository_organization }}/${{ matrix.package.repository_name }}/
#          path: './temp/changelog/${{ matrix.package.repository_organization }}/${{ matrix.package.repository_name }}/'
#          ref: ${{ env.RELEASE_VERSION }}
#          token: ${{ steps.generate_token_changelog.outputs.token }}
      - name: Commit and push
        id: auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'fix: Add changelogs for package ${{ matrix.package.repository_name }}/'
          branch: release-changelog--main
          create_branch: true
      - name: "Run if changes have been detected"
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        run: echo "Changes!"
      - name: "Run if no changes have been detected"
        if: steps.auto-commit-action.outputs.changes_detected == 'false'
        run: echo "No Changes!"
